<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml" lang="ja">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <title>5. 組み込み例外 &#8212; Python 3.6.1 ドキュメント</title>
    
    <link rel="stylesheet" href="../_static/pydoctheme.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    '../',
        VERSION:     '3.6.1',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true
      };
    </script>
    <script type="text/javascript" src="../_static/jquery.js"></script>
    <script type="text/javascript" src="../_static/underscore.js"></script>
    <script type="text/javascript" src="../_static/doctools.js"></script>
    <script type="text/javascript" src="../_static/translations.js"></script>
    <script type="text/javascript" src="../_static/sidebar.js"></script>
    <link rel="search" type="application/opensearchdescription+xml"
          title="Python 3.6.1 ドキュメント 内を検索"
          href="../_static/opensearch.xml"/>
    <link rel="author" title="このドキュメントについて" href="../about.html" />
    <link rel="index" title="索引" href="../genindex.html" />
    <link rel="search" title="検索" href="../search.html" />
    <link rel="copyright" title="Copyright" href="../copyright.html" />
    <link rel="top" title="Python 3.6.1 ドキュメント" href="../contents.html" />
    <link rel="up" title="Python 標準ライブラリ" href="index.html" />
    <link rel="next" title="6. テキスト処理サービス" href="text.html" />
    <link rel="prev" title="4. 組み込み型" href="stdtypes.html" />
    <link rel="shortcut icon" type="image/png" href="../_static/py.png" />
    <link rel="canonical" href="https://docs.python.jp/3/library/exceptions.html" /><script type="text/javascript">
    $(document).ready(function() {
      var base = 'https://docs.python.org/3.6/library/exceptions.html';
      $('a.headerlink').each(function() {
        var html = '<a href="' + base + $(this).attr('href') +
                   '" title="原文へのリンク"><small>(原文)</small></a>';
        $(this).after(html);
      })
    });
    </script>
    <script type="text/javascript" src="../_static/copybutton.js"></script>
    <script type="text/javascript" src="../_static/version_switch.js"></script>
    
    
 

  </head>
  <body role="document">  
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>ナビゲーション</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="総索引"
             accesskey="I">索引</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Pythonモジュール索引"
             >モジュール</a> |</li>
        <li class="right" >
          <a href="text.html" title="6. テキスト処理サービス"
             accesskey="N">次へ</a> |</li>
        <li class="right" >
          <a href="stdtypes.html" title="4. 組み込み型"
             accesskey="P">前へ</a> |</li>
        <li><img src="../_static/py.png" alt=""
                 style="vertical-align: middle; margin-top: -1px"/></li>
        <li><a href="https://www.python.org/">Python</a> &#187;</li>
        <li>
          <span class="version_switcher_placeholder">3.6.1</span>
          <a href="../index.html">ドキュメント</a> &#187;
        </li>

          <li class="nav-item nav-item-1"><a href="index.html" accesskey="U">Python 標準ライブラリ</a> &#187;</li>
    <li class="right">
        

    <div class="inline-search" style="display: none" role="search">
        <form class="inline-search" action="../search.html" method="get">
          <input placeholder="Quick search" type="text" name="q" />
          <input type="submit" value="Go" />
          <input type="hidden" name="check_keywords" value="yes" />
          <input type="hidden" name="area" value="default" />
        </form>
    </div>
    <script type="text/javascript">$('.inline-search').show(0);</script>
         |
    </li>

      </ul>
    </div>    

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body" role="main">
            
  <div class="section" id="built-in-exceptions">
<span id="bltin-exceptions"></span><h1>5. 組み込み例外<a class="headerlink" href="#built-in-exceptions" title="このヘッドラインへのパーマリンク">¶</a></h1>
<p id="index-0">Python において、すべての例外は <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-class docutils literal"><span class="pre">BaseException</span></code></a> から派生したクラスのインスタンスでなければなりません。特定のクラスを言及する <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal"><span class="pre">except</span></code></a> 節を伴う <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal"><span class="pre">try</span></code></a> 文において、その節はそのクラスから派生した例外クラスも処理しますが、そのクラスの派生 <em>元</em> の例外クラスは処理しません。サブクラス化の関係にない 2 つの例外クラスは、それらが同じ名前だった場合でも等しくなりえません。</p>
<p id="index-1">以下に挙げる組み込み例外は、インタプリタや組み込み関数によって生成されます。特に注記しないかぎり、これらはエラーの詳しい原因を示す &#8220;関連値 (associated value)&#8221; を持ちます。この値は、複数の情報 (エラーコードや、そのコードを説明する文字列など) の文字列かタプルです。関連値は通常、例外クラスのコンストラクタに引数として渡されます。</p>
<p>ユーザによるコードも組み込み例外を送出できます。これを使って、例外ハンドラをテストしたり、インタプリタが同じ例外を送出する状況と &#8220;ちょうど同じような&#8221; エラー条件であることを報告したりできます。しかし、ユーザのコードが適切でないエラーを送出するのを妨げる方法はないので注意してください。</p>
<p>組み込み例外クラスは新たな例外を定義するためにサブクラス化することができます。新しい例外は、<a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a> クラスかそのサブクラスの一つから派生することをお勧めします。 <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a> からは派生しないで下さい。例外を定義する上での詳しい情報は、 Python チュートリアルの <a class="reference internal" href="../tutorial/errors.html#tut-userexceptions"><span class="std std-ref">ユーザー定義例外</span></a> の項目にあります。</p>
<p><a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal"><span class="pre">except</span></code></a> または <a class="reference internal" href="../reference/compound_stmts.html#finally"><code class="xref std std-keyword docutils literal"><span class="pre">finally</span></code></a> 節内で例外を送出 (または再送出) するとき、<code class="xref py py-attr docutils literal"><span class="pre">__context__</span></code> は自動的に最後に捕まった例外に設定されます。新しい例外が処理されなければ、最終的に表示されるトレースバックは先に起きた例外も最後の例外も含みます。</p>
<p>現在処理中の例外を <code class="docutils literal"><span class="pre">raise</span></code> を使って再送出するのではなく新規に例外を送出する場合、<a class="reference internal" href="../reference/simple_stmts.html#raise"><code class="xref std std-keyword docutils literal"><span class="pre">raise</span></code></a> と一緒に <a class="reference internal" href="../reference/simple_stmts.html#from"><code class="xref std std-keyword docutils literal"><span class="pre">from</span></code></a> を使うことで暗黙の例外コンテキストを捕捉することができます:</p>
<div class="highlight-python3"><div class="highlight"><pre><span></span><span class="k">raise</span> <span class="n">new_exc</span> <span class="kn">from</span> <span class="nn">original_exc</span>
</pre></div>
</div>
<p><a class="reference internal" href="../reference/simple_stmts.html#from"><code class="xref std std-keyword docutils literal"><span class="pre">from</span></code></a> に続く式 (expression) は例外か <code class="docutils literal"><span class="pre">None</span></code> でなくてはなりません。式は送出される例外の <code class="xref py py-attr docutils literal"><span class="pre">__cause__</span></code> として設定されます。 <code class="xref py py-attr docutils literal"><span class="pre">__cause__</span></code> を設定することは、 <code class="xref py py-attr docutils literal"><span class="pre">__suppress_context__</span></code> 属性を <code class="docutils literal"><span class="pre">True</span></code> にすることも意味するので、 <code class="docutils literal"><span class="pre">raise</span> <span class="pre">new_exc</span> <span class="pre">from</span> <span class="pre">None</span></code> を使うことで効率的に古い例外を新しいもので置き換えて表示する (たとえば <a class="reference internal" href="#KeyError" title="KeyError"><code class="xref py py-exc docutils literal"><span class="pre">KeyError</span></code></a> を <a class="reference internal" href="#AttributeError" title="AttributeError"><code class="xref py py-exc docutils literal"><span class="pre">AttributeError</span></code></a> に置き換え、古い例外はデバッグ時の調査で使えるよう <code class="xref py py-attr docutils literal"><span class="pre">__context__</span></code> に残す) ことができます。</p>
<p>デフォルトの traceback 表示コードは、例外自体の traceback に加え、これらの連鎖された例外を表示します。<code class="xref py py-attr docutils literal"><span class="pre">__cause__</span></code> で明示的に連鎖させた例外は、存在するならば常に表示されます。<code class="xref py py-attr docutils literal"><span class="pre">__context__</span></code> で暗黙に連鎖させた例外は、<code class="xref py py-attr docutils literal"><span class="pre">__cause__</span></code> が <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal"><span class="pre">None</span></code></a> かつ <code class="xref py py-attr docutils literal"><span class="pre">__suppress_context__</span></code> が false の場合にのみ表示されます。</p>
<p>いずれにせよ、連鎖された例外に続いて、その例外自体は常に表示されます。そのため、traceback の最終行には、常に送出された最後の例外が表示されます。</p>
<div class="section" id="base-classes">
<h2>5.1. 基底クラス<a class="headerlink" href="#base-classes" title="このヘッドラインへのパーマリンク">¶</a></h2>
<p>以下の例外は、主に他の例外の基底クラスとして使われます。</p>
<dl class="exception">
<dt id="BaseException">
<em class="property">exception </em><code class="descname">BaseException</code><a class="headerlink" href="#BaseException" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>全ての組み込み例外の基底クラスです。ユーザ定義の例外に直接継承されることは意図されていません (継承には <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a> を使ってください)。このクラスのインスタンスに <a class="reference internal" href="stdtypes.html#str" title="str"><code class="xref py py-func docutils literal"><span class="pre">str()</span></code></a> が呼ばれた場合、インスタンスへの引数の表現か、引数が無い場合には空文字列が返されます。</p>
<dl class="attribute">
<dt id="BaseException.args">
<code class="descname">args</code><a class="headerlink" href="#BaseException.args" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>例外コンストラクタに与えられた引数のタプルです。組み込み例外は普通、エラーメッセージを与える一つの文字列だけを引数として呼ばれますが、中には (<a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a> など) いくつかの引数を必要とし、このタプルの要素に特別な意味を込めるものもあります。</p>
</dd></dl>

<dl class="method">
<dt id="BaseException.with_traceback">
<code class="descname">with_traceback</code><span class="sig-paren">(</span><em>tb</em><span class="sig-paren">)</span><a class="headerlink" href="#BaseException.with_traceback" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>このメソッドは <em>tb</em> を例外の新しいトレースバックとして設定し、例外オブジェクトを返します。これは通常次のような例外処理コードに使われます:</p>
<div class="highlight-python3"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span> <span class="n">SomeException</span><span class="p">:</span>
    <span class="n">tb</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()[</span><span class="mi">2</span><span class="p">]</span>
    <span class="k">raise</span> <span class="n">OtherException</span><span class="p">(</span><span class="o">...</span><span class="p">)</span><span class="o">.</span><span class="n">with_traceback</span><span class="p">(</span><span class="n">tb</span><span class="p">)</span>
</pre></div>
</div>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="Exception">
<em class="property">exception </em><code class="descname">Exception</code><a class="headerlink" href="#Exception" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>システム終了以外の全ての組み込み例外はこのクラスから派生しています。全てのユーザ定義例外もこのクラスから派生させるべきです。</p>
</dd></dl>

<dl class="exception">
<dt id="ArithmeticError">
<em class="property">exception </em><code class="descname">ArithmeticError</code><a class="headerlink" href="#ArithmeticError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>算術上の様々なエラーに対して送出される組み込み例外 <a class="reference internal" href="#OverflowError" title="OverflowError"><code class="xref py py-exc docutils literal"><span class="pre">OverflowError</span></code></a>, <a class="reference internal" href="#ZeroDivisionError" title="ZeroDivisionError"><code class="xref py py-exc docutils literal"><span class="pre">ZeroDivisionError</span></code></a>, <a class="reference internal" href="#FloatingPointError" title="FloatingPointError"><code class="xref py py-exc docutils literal"><span class="pre">FloatingPointError</span></code></a> の基底クラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="BufferError">
<em class="property">exception </em><code class="descname">BufferError</code><a class="headerlink" href="#BufferError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p><a class="reference internal" href="../c-api/buffer.html#bufferobjects"><span class="std std-ref">バッファ</span></a> に関連する操作が行えなかったときに送出されます。</p>
</dd></dl>

<dl class="exception">
<dt id="LookupError">
<em class="property">exception </em><code class="descname">LookupError</code><a class="headerlink" href="#LookupError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>マッピングまたはシーケンスで使われたキーやインデクスが無効な場合に送出される例外 <a class="reference internal" href="#IndexError" title="IndexError"><code class="xref py py-exc docutils literal"><span class="pre">IndexError</span></code></a> および <a class="reference internal" href="#KeyError" title="KeyError"><code class="xref py py-exc docutils literal"><span class="pre">KeyError</span></code></a> の基底クラスです。 <a class="reference internal" href="codecs.html#codecs.lookup" title="codecs.lookup"><code class="xref py py-func docutils literal"><span class="pre">codecs.lookup()</span></code></a> によって直接送出されることもあります。</p>
</dd></dl>

</div>
<div class="section" id="concrete-exceptions">
<h2>5.2. 具象例外<a class="headerlink" href="#concrete-exceptions" title="このヘッドラインへのパーマリンク">¶</a></h2>
<p>以下の例外は、通常送出される例外です。</p>
<dl class="exception">
<dt id="AssertionError">
<em class="property">exception </em><code class="descname">AssertionError</code><a class="headerlink" href="#AssertionError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p id="index-2"><a class="reference internal" href="../reference/simple_stmts.html#assert"><code class="xref std std-keyword docutils literal"><span class="pre">assert</span></code></a> 文が失敗した場合に送出されます。</p>
</dd></dl>

<dl class="exception">
<dt id="AttributeError">
<em class="property">exception </em><code class="descname">AttributeError</code><a class="headerlink" href="#AttributeError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>属性参照 (<a class="reference internal" href="../reference/expressions.html#attribute-references"><span class="std std-ref">属性参照</span></a> を参照) や代入が失敗した場合に送出されます (オブジェクトが属性の参照や属性の代入をまったくサポートしていない場合には <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal"><span class="pre">TypeError</span></code></a> が送出されます)。</p>
</dd></dl>

<dl class="exception">
<dt id="EOFError">
<em class="property">exception </em><code class="descname">EOFError</code><a class="headerlink" href="#EOFError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p><a class="reference internal" href="functions.html#input" title="input"><code class="xref py py-func docutils literal"><span class="pre">input()</span></code></a> が何もデータを読まずに end-of-file (EOF) に達した場合に送出されます。(注意:  <code class="xref py py-meth docutils literal"><span class="pre">io.IOBase.read()</span></code> と <a class="reference internal" href="io.html#io.IOBase.readline" title="io.IOBase.readline"><code class="xref py py-meth docutils literal"><span class="pre">io.IOBase.readline()</span></code></a> メソッドは、EOF に達すると空文字列を返します。)</p>
</dd></dl>

<dl class="exception">
<dt id="FloatingPointError">
<em class="property">exception </em><code class="descname">FloatingPointError</code><a class="headerlink" href="#FloatingPointError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>浮動小数点演算が失敗した場合に送出されます。この例外は Python のどのバージョンでも常に定義されていますが、 Python が <code class="docutils literal"><span class="pre">--with-fpectl</span></code> オプションを有効にしてコンパイルされているか、 <code class="file docutils literal"><span class="pre">pyconfig.h</span></code> ファイルにシンボル <code class="xref py py-const docutils literal"><span class="pre">WANT_SIGFPE_HANDLER</span></code> が定義されている場合にのみ送出されます。</p>
</dd></dl>

<dl class="exception">
<dt id="GeneratorExit">
<em class="property">exception </em><code class="descname">GeneratorExit</code><a class="headerlink" href="#GeneratorExit" title="この定義へのパーマリンク">¶</a></dt>
<dd><p><a class="reference internal" href="../glossary.html#term-generator"><span class="xref std std-term">ジェネレータ</span></a> や <a class="reference internal" href="../glossary.html#term-coroutine"><span class="xref std std-term">コルーチン</span></a> が閉じられたときに送出されます。 <a class="reference internal" href="../reference/expressions.html#generator.close" title="generator.close"><code class="xref py py-meth docutils literal"><span class="pre">generator.close()</span></code></a> と <a class="reference internal" href="../reference/datamodel.html#coroutine.close" title="coroutine.close"><code class="xref py py-meth docutils literal"><span class="pre">coroutine.close()</span></code></a> を参照してください。この例外はエラーではなく技術的なものなので、 <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a> ではなく <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a> を直接継承しています。</p>
</dd></dl>

<dl class="exception">
<dt id="ImportError">
<em class="property">exception </em><code class="descname">ImportError</code><a class="headerlink" href="#ImportError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>Raised when the <a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal"><span class="pre">import</span></code></a> statement has troubles trying to
load a module.  Also raised when the &#8220;from list&#8221; in <code class="docutils literal"><span class="pre">from</span> <span class="pre">...</span> <span class="pre">import</span></code>
has a name that cannot be found.</p>
<p>コンストラクタのキーワード専用引数を使って <code class="xref py py-attr docutils literal"><span class="pre">name</span></code> および <code class="xref py py-attr docutils literal"><span class="pre">path</span></code> 属性を設定できます。設定された場合、インポートを試みられたモジュールの名前と、例外を引き起こしたファイルへのパスとを、それぞれ表します。</p>
<div class="versionchanged">
<p><span class="versionmodified">バージョン 3.3 で変更: </span><code class="xref py py-attr docutils literal"><span class="pre">name</span></code> および <code class="xref py py-attr docutils literal"><span class="pre">path</span></code> 属性が追加されました。</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="ModuleNotFoundError">
<em class="property">exception </em><code class="descname">ModuleNotFoundError</code><a class="headerlink" href="#ModuleNotFoundError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ImportError" title="ImportError"><code class="xref py py-exc docutils literal"><span class="pre">ImportError</span></code></a> which is raised by <a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal"><span class="pre">import</span></code></a>
when a module could not be located.  It is also raised when <code class="docutils literal"><span class="pre">None</span></code>
is found in <a class="reference internal" href="sys.html#sys.modules" title="sys.modules"><code class="xref py py-data docutils literal"><span class="pre">sys.modules</span></code></a>.</p>
<div class="versionadded">
<p><span class="versionmodified">バージョン 3.6 で追加.</span></p>
</div>
</dd></dl>

<dl class="exception">
<dt id="IndexError">
<em class="property">exception </em><code class="descname">IndexError</code><a class="headerlink" href="#IndexError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>シーケンスの添字が範囲外の場合に送出されます。 (スライスのインデクスはシーケンスの範囲に収まるように暗黙のうちに調整されます; インデクスが整数でない場合、 <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal"><span class="pre">TypeError</span></code></a> が送出されます。)</p>
</dd></dl>

<dl class="exception">
<dt id="KeyError">
<em class="property">exception </em><code class="descname">KeyError</code><a class="headerlink" href="#KeyError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>マッピング (辞書) のキーが、既存のキーの集合内に見つからなかった場合に送出されます。</p>
</dd></dl>

<dl class="exception">
<dt id="KeyboardInterrupt">
<em class="property">exception </em><code class="descname">KeyboardInterrupt</code><a class="headerlink" href="#KeyboardInterrupt" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>ユーザが割り込みキー (通常は <code class="kbd docutils literal"><span class="pre">Control-C</span></code> または <code class="kbd docutils literal"><span class="pre">Delete</span></code>) を押した場合に送出されます。実行中、割り込みは定期的に監視されます。<a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a> を捕捉するコードに誤って捕捉されてインタプリタの終了が阻害されないように、この例外は <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a> を継承しています。</p>
</dd></dl>

<dl class="exception">
<dt id="MemoryError">
<em class="property">exception </em><code class="descname">MemoryError</code><a class="headerlink" href="#MemoryError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>ある操作中にメモリが不足したが、その状況は (オブジェクトをいくつか消去することで) まだ復旧可能かもしれない場合に送出されます。この例外の関連値は、メモリ不足になった (内部) 操作の種類を示す文字列です。下層のメモリ管理アーキテクチャ (C の <code class="xref c c-func docutils literal"><span class="pre">malloc()</span></code> 関数) のために、インタプリタが現状から完璧に復旧できるとはかぎらないので注意してください。それでも、プログラムの暴走が原因の場合に備えて実行スタックのトレースバックを出力できるように、例外が送出されます。</p>
</dd></dl>

<dl class="exception">
<dt id="NameError">
<em class="property">exception </em><code class="descname">NameError</code><a class="headerlink" href="#NameError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>ローカルまたはグローバルの名前が見つからなかった場合に送出されます。これは非修飾の (訳注: <code class="docutils literal"><span class="pre">spam.egg</span></code> ではなく単に <code class="docutils literal"><span class="pre">egg</span></code> のような) 名前のみに適用されます。関連値は見つからなかった名前を含むエラーメッセージです。</p>
</dd></dl>

<dl class="exception">
<dt id="NotImplementedError">
<em class="property">exception </em><code class="descname">NotImplementedError</code><a class="headerlink" href="#NotImplementedError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>This exception is derived from <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal"><span class="pre">RuntimeError</span></code></a>.  In user defined base
classes, abstract methods should raise this exception when they require
derived classes to override the method, or while the class is being
developed to indicate that the real implementation still needs to be added.</p>
<div class="admonition note">
<p class="first admonition-title">注釈</p>
<p class="last">It should not be used to indicate that an operater or method is not
meant to be supported at all &#8211; in that case either leave the operator /
method undefined or, if a subclass, set it to <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-data docutils literal"><span class="pre">None</span></code></a>.</p>
</div>
<div class="admonition note">
<p class="first admonition-title">注釈</p>
<p class="last"><code class="docutils literal"><span class="pre">NotImplementedError</span></code> and <code class="docutils literal"><span class="pre">NotImplemented</span></code> are not interchangeable,
even though they have similar names and purposes.  See
<a class="reference internal" href="constants.html#NotImplemented" title="NotImplemented"><code class="xref py py-data docutils literal"><span class="pre">NotImplemented</span></code></a> for details on when to use it.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="OSError">
<em class="property">exception </em><code class="descname">OSError</code><span class="sig-paren">(</span><span class="optional">[</span><em>arg</em><span class="optional">]</span><span class="sig-paren">)</span><a class="headerlink" href="#OSError" title="この定義へのパーマリンク">¶</a></dt>
<dt>
<em class="property">exception </em><code class="descname">OSError</code><span class="sig-paren">(</span><em>errno</em>, <em>strerror</em><span class="optional">[</span>, <em>filename</em><span class="optional">[</span>, <em>winerror</em><span class="optional">[</span>, <em>filename2</em><span class="optional">]</span><span class="optional">]</span><span class="optional">]</span><span class="sig-paren">)</span></dt>
<dd><p id="index-3">この例外はシステム関数がシステム関連のエラーを返した場合に送出されます。例えば &#8220;file not found&#8221; や &#8220;disk full&#8221; のような I/O の失敗が発生したときです (引数の型が不正な場合や、他の偶発的なエラーは除きます)。</p>
<p>コンストラクタの2番目の形式は下記の対応する属性を設定します。指定されなかった場合属性はデフォルトで <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal"><span class="pre">None</span></code></a> です。後方互換性のために、引数が3つ渡された場合、<a class="reference internal" href="#BaseException.args" title="BaseException.args"><code class="xref py py-attr docutils literal"><span class="pre">args</span></code></a> 属性は最初の2つの要素のみからなるタプルを持ちます。</p>
<p>コンストラクタは実際には、 <a class="reference internal" href="#os-exceptions">OS exceptions</a> で述べられている <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a> のサブクラスを返すことがよくあります。特定のサブクラスは最終的な <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal"><span class="pre">errno</span></code></a> 値によります。この挙動は <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a> を直接またはエイリアスで構築し、サブクラス化時に継承されなかった場合にのみ発生します。</p>
<dl class="attribute">
<dt id="OSError.errno">
<code class="descname">errno</code><a class="headerlink" href="#OSError.errno" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>C 変数 <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> に由来する数値エラーコードです。</p>
</dd></dl>

<dl class="attribute">
<dt id="OSError.winerror">
<code class="descname">winerror</code><a class="headerlink" href="#OSError.winerror" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>Windows において、ネイティブ Windows エラーコードを与えます。そして <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal"><span class="pre">errno</span></code></a> 属性は POSIX でいうネイティブエラーコードへのおよその翻訳です。</p>
<p>Windows では、<em>winerror</em> コンストラクタ引数が整数の場合 <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal"><span class="pre">errno</span></code></a> 属性は Windows エラーコードから決定され、<em>errno</em> 引数は無視されます。他のプラットフォームでは <em>winerror</em> 引数は無視され、 <a class="reference internal" href="#OSError.winerror" title="OSError.winerror"><code class="xref py py-attr docutils literal"><span class="pre">winerror</span></code></a> 属性は存在しません。</p>
</dd></dl>

<dl class="attribute">
<dt id="OSError.strerror">
<code class="descname">strerror</code><a class="headerlink" href="#OSError.strerror" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>OS が提供するような、対応するエラーメッセージです。
POSIX では <code class="xref c c-func docutils literal"><span class="pre">perror()</span></code> で、Windows では <code class="xref c c-func docutils literal"><span class="pre">FormatMessage()</span></code> で体裁化されます。</p>
</dd></dl>

<dl class="attribute">
<dt id="OSError.filename">
<code class="descname">filename</code><a class="headerlink" href="#OSError.filename" title="この定義へのパーマリンク">¶</a></dt>
<dt id="OSError.filename2">
<code class="descname">filename2</code><a class="headerlink" href="#OSError.filename2" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>ファイルシステムパスが1つ関与する例外 (例えば <a class="reference internal" href="functions.html#open" title="open"><code class="xref py py-func docutils literal"><span class="pre">open()</span></code></a> や <a class="reference internal" href="os.html#os.unlink" title="os.unlink"><code class="xref py py-func docutils literal"><span class="pre">os.unlink()</span></code></a>) の場合、<a class="reference internal" href="#OSError.filename" title="OSError.filename"><code class="xref py py-attr docutils literal"><span class="pre">filename</span></code></a> は関数に渡されたファイル名です。
ファイルシステムパスが2つ関与する関数 (例えば <a class="reference internal" href="os.html#os.rename" title="os.rename"><code class="xref py py-func docutils literal"><span class="pre">os.rename()</span></code></a>) の場合、<a class="reference internal" href="#OSError.filename2" title="OSError.filename2"><code class="xref py py-attr docutils literal"><span class="pre">filename2</span></code></a> は関数に渡された2つ目のファイル名です。</p>
</dd></dl>

<div class="versionchanged">
<p><span class="versionmodified">バージョン 3.3 で変更: </span><a class="reference internal" href="#EnvironmentError" title="EnvironmentError"><code class="xref py py-exc docutils literal"><span class="pre">EnvironmentError</span></code></a>, <a class="reference internal" href="#IOError" title="IOError"><code class="xref py py-exc docutils literal"><span class="pre">IOError</span></code></a>, <a class="reference internal" href="#WindowsError" title="WindowsError"><code class="xref py py-exc docutils literal"><span class="pre">WindowsError</span></code></a>, <a class="reference internal" href="socket.html#socket.error" title="socket.error"><code class="xref py py-exc docutils literal"><span class="pre">socket.error</span></code></a>, <a class="reference internal" href="select.html#select.error" title="select.error"><code class="xref py py-exc docutils literal"><span class="pre">select.error</span></code></a>, <code class="xref py py-exc docutils literal"><span class="pre">mmap.error</span></code> が <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a> に統合されました。コンストラクタはサブクラスを返すかもしれません。</p>
</div>
<div class="versionchanged">
<p><span class="versionmodified">バージョン 3.4 で変更: </span><a class="reference internal" href="#OSError.filename" title="OSError.filename"><code class="xref py py-attr docutils literal"><span class="pre">filename</span></code></a> 属性がファイルシステムのエンコーディングでエンコードやデコードされた名前から、関数に渡された元々のファイル名になりました。
また、<em>filename2</em> コンストラクタ引数が追加されました。</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="OverflowError">
<em class="property">exception </em><code class="descname">OverflowError</code><a class="headerlink" href="#OverflowError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>算術演算の結果が表現できない大きな値になった場合に送出されます。これは整数では起こりません (むしろ <a class="reference internal" href="#MemoryError" title="MemoryError"><code class="xref py py-exc docutils literal"><span class="pre">MemoryError</span></code></a> が送出されることになるでしょう)。しかし、歴史的な理由のため、要求された範囲の外の整数に対して OverflowError が送出されることがあります。C の浮動小数点演算の例外処理は標準化されていないので、ほとんどの浮動小数点演算もチェックされません。</p>
</dd></dl>

<dl class="exception">
<dt id="RecursionError">
<em class="property">exception </em><code class="descname">RecursionError</code><a class="headerlink" href="#RecursionError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>この例外は <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal"><span class="pre">RuntimeError</span></code></a> を継承しています。インタープリタが最大再帰深度 (<a class="reference internal" href="sys.html#sys.getrecursionlimit" title="sys.getrecursionlimit"><code class="xref py py-func docutils literal"><span class="pre">sys.getrecursionlimit()</span></code></a> を参照) の超過を検出すると送出されます。</p>
<div class="versionadded">
<p><span class="versionmodified">バージョン 3.5 で追加: </span>以前は <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal"><span class="pre">RuntimeError</span></code></a> をそのまま送出していました。</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="ReferenceError">
<em class="property">exception </em><code class="descname">ReferenceError</code><a class="headerlink" href="#ReferenceError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p><a class="reference internal" href="weakref.html#weakref.proxy" title="weakref.proxy"><code class="xref py py-func docutils literal"><span class="pre">weakref.proxy()</span></code></a> によって生成された弱参照 (weak reference) プロキシを使って、ガーベジコレクションによって回収された後の参照対象オブジェクトの属性にアクセスした場合に送出されます。弱参照については <a class="reference internal" href="weakref.html#module-weakref" title="weakref: Support for weak references and weak dictionaries."><code class="xref py py-mod docutils literal"><span class="pre">weakref</span></code></a> モジュールを参照してください。</p>
</dd></dl>

<dl class="exception">
<dt id="RuntimeError">
<em class="property">exception </em><code class="descname">RuntimeError</code><a class="headerlink" href="#RuntimeError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>他のカテゴリに分類できないエラーが検出された場合に送出されます。関連値は、何が問題だったのかをより詳細に示す文字列です。</p>
</dd></dl>

<dl class="exception">
<dt id="StopIteration">
<em class="property">exception </em><code class="descname">StopIteration</code><a class="headerlink" href="#StopIteration" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>組込み関数 <a class="reference internal" href="functions.html#next" title="next"><code class="xref py py-func docutils literal"><span class="pre">next()</span></code></a> と <a class="reference internal" href="../glossary.html#term-iterator"><span class="xref std std-term">iterator</span></a> の <a class="reference internal" href="stdtypes.html#iterator.__next__" title="iterator.__next__"><code class="xref py py-meth docutils literal"><span class="pre">__next__()</span></code></a> メソッドによって、そのイテレータが生成するアイテムがこれ以上ないことを伝えるために送出されます。</p>
<p>この例外オブジェクトには一つの属性 <code class="xref py py-attr docutils literal"><span class="pre">value</span></code> があり、例外を構成する際に引数として与えられ、デフォルトは <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal"><span class="pre">None</span></code></a> です。</p>
<p><a class="reference internal" href="../glossary.html#term-generator"><span class="xref std std-term">generator</span></a> や <a class="reference internal" href="../glossary.html#term-coroutine"><span class="xref std std-term">coroutine</span></a> 関数が返るとき、新しい <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal"><span class="pre">StopIteration</span></code></a> インスタンスが送出されます。
関数の返り値は例外のコンストラクタの <code class="xref py py-attr docutils literal"><span class="pre">value</span></code> 引数として使われます。</p>
<p><code class="docutils literal"><span class="pre">from</span> <span class="pre">__future__</span> <span class="pre">import</span> <span class="pre">generator_stop</span></code> が宣言されている条件下では、ジェネレータ関数が投げる <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal"><span class="pre">StopIteration</span></code></a> は <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal"><span class="pre">RuntimeError</span></code></a> に変換されます (<a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal"><span class="pre">StopIteration</span></code></a> は変換後の例外の原因例外として保持されます)。</p>
<div class="versionchanged">
<p><span class="versionmodified">バージョン 3.3 で変更: </span><code class="docutils literal"><span class="pre">value</span></code> 属性とジェネレータ関数が値を返すためにそれを使う機能が追加されました。</p>
</div>
<div class="versionchanged">
<p><span class="versionmodified">バージョン 3.5 で変更: </span>RuntimeError への変換が導入されました。</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="StopAsyncIteration">
<em class="property">exception </em><code class="descname">StopAsyncIteration</code><a class="headerlink" href="#StopAsyncIteration" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>イテレーションを停止するために、 <a class="reference internal" href="../glossary.html#term-asynchronous-iterator"><span class="xref std std-term">asynchronous iterator</span></a> オブジェクトの <a class="reference internal" href="../reference/datamodel.html#object.__anext__" title="object.__anext__"><code class="xref py py-meth docutils literal"><span class="pre">__anext__()</span></code></a> メソッドによって返される必要があります。</p>
<div class="versionadded">
<p><span class="versionmodified">バージョン 3.5 で追加.</span></p>
</div>
</dd></dl>

<dl class="exception">
<dt id="SyntaxError">
<em class="property">exception </em><code class="descname">SyntaxError</code><a class="headerlink" href="#SyntaxError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>パーザが構文エラーに遭遇した場合に送出されます。この例外は <a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal"><span class="pre">import</span></code></a> 文、組み込み関数 <a class="reference internal" href="functions.html#exec" title="exec"><code class="xref py py-func docutils literal"><span class="pre">exec()</span></code></a> や <a class="reference internal" href="functions.html#eval" title="eval"><code class="xref py py-func docutils literal"><span class="pre">eval()</span></code></a> 、初期化スクリプトの読み込みや標準入力で (対話的な実行時にも) 起こる可能性があります。</p>
<p>このクラスのインスタンスは、例外の詳細に簡単にアクセスできるようにするために、属性 <code class="xref py py-attr docutils literal"><span class="pre">filename</span></code>, <code class="xref py py-attr docutils literal"><span class="pre">lineno</span></code>, <code class="xref py py-attr docutils literal"><span class="pre">offset</span></code>, <code class="xref py py-attr docutils literal"><span class="pre">text</span></code> を持ちます。例外インスタンスに対する <a class="reference internal" href="stdtypes.html#str" title="str"><code class="xref py py-func docutils literal"><span class="pre">str()</span></code></a> はメッセージのみを返します。</p>
</dd></dl>

<dl class="exception">
<dt id="IndentationError">
<em class="property">exception </em><code class="descname">IndentationError</code><a class="headerlink" href="#IndentationError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>正しくないインデントに関する構文エラーの基底クラスです。これは <a class="reference internal" href="#SyntaxError" title="SyntaxError"><code class="xref py py-exc docutils literal"><span class="pre">SyntaxError</span></code></a> のサブクラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="TabError">
<em class="property">exception </em><code class="descname">TabError</code><a class="headerlink" href="#TabError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>タブとスペースを一貫しない方法でインデントに使っているときに送出されます。これは <a class="reference internal" href="#IndentationError" title="IndentationError"><code class="xref py py-exc docutils literal"><span class="pre">IndentationError</span></code></a> のサブクラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="SystemError">
<em class="property">exception </em><code class="descname">SystemError</code><a class="headerlink" href="#SystemError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>インタプリタが内部エラーを発見したが、状況は全ての望みを棄てさせるほど深刻ではないと思われる場合に送出されます。関連値は (下位層で) どの動作が失敗したかを示す文字列です。</p>
<p>使用中の Python インタプリタの作者または保守担当者にこのエラーを報告してください。このとき、Python インタプリタのバージョン (<code class="docutils literal"><span class="pre">sys.version</span></code> 。Python の対話的セッションを開始した際にも出力されます)、正確なエラーメッセージ (例外の関連値) を忘れずに報告してください。可能な場合にはエラーを引き起こしたプログラムのソースコードも報告してください。</p>
</dd></dl>

<dl class="exception">
<dt id="SystemExit">
<em class="property">exception </em><code class="descname">SystemExit</code><a class="headerlink" href="#SystemExit" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>この例外は <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal"><span class="pre">sys.exit()</span></code></a> 関数から送出されます。<a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a> をキャッチするコードに誤ってキャッチされないように、<a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a> ではなく <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a> を継承しています。これにより例外は上の階層に適切に伝わり、インタープリタを終了させます。この例外が処理されなかった場合はスタックのトレースバックを表示せずに Python インタープリタは終了します。コンストラクタは <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal"><span class="pre">sys.exit()</span></code></a> に渡されるオプション引数と同じものを受け取ります。値が整数の場合、システムの終了ステータス (C 言語の <code class="xref c c-func docutils literal"><span class="pre">exit()</span></code> 関数に渡すもの)を指定します。値が <code class="docutils literal"><span class="pre">None</span></code> の場合、終了ステータスは 0 です。それ以外の型の場合 (例えば str)、 オブジェクトの値が表示され、終了ステータスは 1 です。</p>
<p><a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal"><span class="pre">sys.exit()</span></code></a> は、クリーンアップのための処理 (<a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal"><span class="pre">try</span></code></a> 文の <a class="reference internal" href="../reference/compound_stmts.html#finally"><code class="xref std std-keyword docutils literal"><span class="pre">finally</span></code></a> 節) が実行されるようにするため、またデバッガが制御不能になるリスクを冒さずにスクリプトを実行できるようにするために例外に変換されます。即座に終了することが真に強く必要であるとき (例えば、<a class="reference internal" href="os.html#os.fork" title="os.fork"><code class="xref py py-func docutils literal"><span class="pre">os.fork()</span></code></a> を呼んだ後の子プロセス内) には <a class="reference internal" href="os.html#os._exit" title="os._exit"><code class="xref py py-func docutils literal"><span class="pre">os._exit()</span></code></a> 関数を使うことができます。</p>
<dl class="attribute">
<dt id="SystemExit.code">
<code class="descname">code</code><a class="headerlink" href="#SystemExit.code" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>コンストラクタに渡された終了ステータス又はエラーメッセージ。(デフォルトは <code class="docutils literal"><span class="pre">None</span></code>)</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="TypeError">
<em class="property">exception </em><code class="descname">TypeError</code><a class="headerlink" href="#TypeError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>組み込み演算または関数が適切でない型のオブジェクトに対して適用された際に送出されます。関連値は型の不整合に関して詳細を述べた文字列です。</p>
<p>This exception may be raised by user code to indicate that an attempted
operation on an object is not supported, and is not meant to be. If an object
is meant to support a given operation but has not yet provided an
implementation, <a class="reference internal" href="#NotImplementedError" title="NotImplementedError"><code class="xref py py-exc docutils literal"><span class="pre">NotImplementedError</span></code></a> is the proper exception to raise.</p>
<p>Passing arguments of the wrong type (e.g. passing a <a class="reference internal" href="stdtypes.html#list" title="list"><code class="xref py py-class docutils literal"><span class="pre">list</span></code></a> when an
<a class="reference internal" href="functions.html#int" title="int"><code class="xref py py-class docutils literal"><span class="pre">int</span></code></a> is expected) should result in a <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal"><span class="pre">TypeError</span></code></a>, but passing
arguments with the wrong value (e.g. a number outside expected boundaries)
should result in a <a class="reference internal" href="#ValueError" title="ValueError"><code class="xref py py-exc docutils literal"><span class="pre">ValueError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="UnboundLocalError">
<em class="property">exception </em><code class="descname">UnboundLocalError</code><a class="headerlink" href="#UnboundLocalError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>関数やメソッド内のローカルな変数に対して参照を行ったが、その変数には値が代入されていなかった場合に送出されます。 <a class="reference internal" href="#NameError" title="NameError"><code class="xref py py-exc docutils literal"><span class="pre">NameError</span></code></a> のサブクラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="UnicodeError">
<em class="property">exception </em><code class="descname">UnicodeError</code><a class="headerlink" href="#UnicodeError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>Unicode に関するエンコードまたはデコードのエラーが発生した際に送出されます。 <a class="reference internal" href="#ValueError" title="ValueError"><code class="xref py py-exc docutils literal"><span class="pre">ValueError</span></code></a> のサブクラスです。</p>
<p><a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></code></a> はエンコードまたはデコードのエラーの説明を属性として持っています。例えば、 <code class="docutils literal"><span class="pre">err.object[err.start:err.end]</span></code> は、無効な入力のうちコーデックが処理に失敗した箇所を表します。</p>
<dl class="attribute">
<dt id="UnicodeError.encoding">
<code class="descname">encoding</code><a class="headerlink" href="#UnicodeError.encoding" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>エラーを送出したエンコーディングの名前です。</p>
</dd></dl>

<dl class="attribute">
<dt id="UnicodeError.reason">
<code class="descname">reason</code><a class="headerlink" href="#UnicodeError.reason" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>そのコーデックエラーを説明する文字列です。</p>
</dd></dl>

<dl class="attribute">
<dt id="UnicodeError.object">
<code class="descname">object</code><a class="headerlink" href="#UnicodeError.object" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>コーデックがエンコードまたはデコードしようとしたオブジェクトです。</p>
</dd></dl>

<dl class="attribute">
<dt id="UnicodeError.start">
<code class="descname">start</code><a class="headerlink" href="#UnicodeError.start" title="この定義へのパーマリンク">¶</a></dt>
<dd><p><a class="reference internal" href="functions.html#object" title="object"><code class="xref py py-attr docutils literal"><span class="pre">object</span></code></a> の最初の無効なデータのインデクスです。</p>
</dd></dl>

<dl class="attribute">
<dt id="UnicodeError.end">
<code class="descname">end</code><a class="headerlink" href="#UnicodeError.end" title="この定義へのパーマリンク">¶</a></dt>
<dd><p><a class="reference internal" href="functions.html#object" title="object"><code class="xref py py-attr docutils literal"><span class="pre">object</span></code></a> の最後の無効なデータの次のインデクスです。</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="UnicodeEncodeError">
<em class="property">exception </em><code class="descname">UnicodeEncodeError</code><a class="headerlink" href="#UnicodeEncodeError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>Unicode 関連のエラーがエンコード中に発生した際に送出されます。 <a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></code></a> のサブクラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="UnicodeDecodeError">
<em class="property">exception </em><code class="descname">UnicodeDecodeError</code><a class="headerlink" href="#UnicodeDecodeError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>Unicode 関連のエラーがデコード中に発生した際に送出されます。 <a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></code></a> のサブクラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="UnicodeTranslateError">
<em class="property">exception </em><code class="descname">UnicodeTranslateError</code><a class="headerlink" href="#UnicodeTranslateError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>Unicode 関連のエラーが変換中に発生した際に送出されます。 <a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></code></a> のサブクラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="ValueError">
<em class="property">exception </em><code class="descname">ValueError</code><a class="headerlink" href="#ValueError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>組み込み演算や関数が、正しい型だが適切でない値を受け取った場合や、 <a class="reference internal" href="#IndexError" title="IndexError"><code class="xref py py-exc docutils literal"><span class="pre">IndexError</span></code></a> のような詳細な例外では説明のできない状況で送出されます。</p>
</dd></dl>

<dl class="exception">
<dt id="ZeroDivisionError">
<em class="property">exception </em><code class="descname">ZeroDivisionError</code><a class="headerlink" href="#ZeroDivisionError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>除算や剰余演算の第二引数が 0 であった場合に送出されます。関連値は文字列で、その演算における被演算子と演算子の型を示します。</p>
</dd></dl>

<p>以下の例外は、過去のバージョンとの後方互換性のために残されています; Python 3.3 より、これらは <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a> のエイリアスです。</p>
<dl class="exception">
<dt id="EnvironmentError">
<em class="property">exception </em><code class="descname">EnvironmentError</code><a class="headerlink" href="#EnvironmentError" title="この定義へのパーマリンク">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="IOError">
<em class="property">exception </em><code class="descname">IOError</code><a class="headerlink" href="#IOError" title="この定義へのパーマリンク">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="WindowsError">
<em class="property">exception </em><code class="descname">WindowsError</code><a class="headerlink" href="#WindowsError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>Windows でのみ利用できます。</p>
</dd></dl>

<div class="section" id="os-exceptions">
<h3>5.2.1. OS 例外<a class="headerlink" href="#os-exceptions" title="このヘッドラインへのパーマリンク">¶</a></h3>
<p>以下の例外は <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a> のサブクラスで、システムエラーコードに依存して送出されます。</p>
<dl class="exception">
<dt id="BlockingIOError">
<em class="property">exception </em><code class="descname">BlockingIOError</code><a class="headerlink" href="#BlockingIOError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>ある操作が、ノンブロッキング操作に設定されたオブジェクト (例えばソケット) をブロックしそうになった場合に送出されます。<code class="xref c c-data docutils literal"><span class="pre">errno</span></code>  <code class="docutils literal"><span class="pre">EAGAIN</span></code>, <code class="docutils literal"><span class="pre">EALREADY</span></code>, <code class="docutils literal"><span class="pre">EWOULDBLOCK</span></code> および <code class="docutils literal"><span class="pre">EINPROGRESS</span></code> に対応します。</p>
<p><a class="reference internal" href="#BlockingIOError" title="BlockingIOError"><code class="xref py py-exc docutils literal"><span class="pre">BlockingIOError</span></code></a> は、 <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a> の属性に加えて一つの属性を持ちます:</p>
<dl class="attribute">
<dt id="BlockingIOError.characters_written">
<code class="descname">characters_written</code><a class="headerlink" href="#BlockingIOError.characters_written" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>ストリームがブロックされるまでに書き込まれた文字数を含む整数です。この属性は <a class="reference internal" href="io.html#module-io" title="io: Core tools for working with streams."><code class="xref py py-mod docutils literal"><span class="pre">io</span></code></a> からのバッファ I/O クラスを使っているときに利用できます。</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="ChildProcessError">
<em class="property">exception </em><code class="descname">ChildProcessError</code><a class="headerlink" href="#ChildProcessError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>子プロセスの操作が失敗した場合に送出されます。<code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ECHILD</span></code> に対応します。</p>
</dd></dl>

<dl class="exception">
<dt id="ConnectionError">
<em class="property">exception </em><code class="descname">ConnectionError</code><a class="headerlink" href="#ConnectionError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>コネクション関係の問題の基底クラス。</p>
<p>サブクラスは <a class="reference internal" href="#BrokenPipeError" title="BrokenPipeError"><code class="xref py py-exc docutils literal"><span class="pre">BrokenPipeError</span></code></a>, <a class="reference internal" href="#ConnectionAbortedError" title="ConnectionAbortedError"><code class="xref py py-exc docutils literal"><span class="pre">ConnectionAbortedError</span></code></a>, <a class="reference internal" href="#ConnectionRefusedError" title="ConnectionRefusedError"><code class="xref py py-exc docutils literal"><span class="pre">ConnectionRefusedError</span></code></a>, <a class="reference internal" href="#ConnectionResetError" title="ConnectionResetError"><code class="xref py py-exc docutils literal"><span class="pre">ConnectionResetError</span></code></a> です。</p>
</dd></dl>

<dl class="exception">
<dt id="BrokenPipeError">
<em class="property">exception </em><code class="descname">BrokenPipeError</code><a class="headerlink" href="#BrokenPipeError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p><a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal"><span class="pre">ConnectionError</span></code></a> のサブクラスで、もう一方の端が閉じられたパイプに書き込こもうとするか、書き込みのためにシャットダウンされたソケットに書き込こもうとした場合に発生します。 <code class="xref c c-data docutils literal"><span class="pre">errno</span></code>  <code class="docutils literal"><span class="pre">EPIPE</span></code> と <code class="docutils literal"><span class="pre">ESHUTDOWN</span></code> に対応します。</p>
</dd></dl>

<dl class="exception">
<dt id="ConnectionAbortedError">
<em class="property">exception </em><code class="descname">ConnectionAbortedError</code><a class="headerlink" href="#ConnectionAbortedError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p><a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal"><span class="pre">ConnectionError</span></code></a> のサブクラスで、接続の試行が通信相手によって中断された場合に発生します。 <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ECONNABORTED</span></code> に対応します。</p>
</dd></dl>

<dl class="exception">
<dt id="ConnectionRefusedError">
<em class="property">exception </em><code class="descname">ConnectionRefusedError</code><a class="headerlink" href="#ConnectionRefusedError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p><a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal"><span class="pre">ConnectionError</span></code></a> のサブクラスで、接続の試行が通信相手によって拒否された場合に発生します。 <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ECONNREFUSED</span></code> に対応します。</p>
</dd></dl>

<dl class="exception">
<dt id="ConnectionResetError">
<em class="property">exception </em><code class="descname">ConnectionResetError</code><a class="headerlink" href="#ConnectionResetError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p><a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal"><span class="pre">ConnectionError</span></code></a> のサブクラスで、接続が通信相手によってリセットされた場合に発生します。 <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ECONNRESET</span></code> に対応します。</p>
</dd></dl>

<dl class="exception">
<dt id="FileExistsError">
<em class="property">exception </em><code class="descname">FileExistsError</code><a class="headerlink" href="#FileExistsError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>すでに存在するファイルやディレクトリを作成しようとした場合に送出されます。<code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">EEXIST</span></code> に対応します。</p>
</dd></dl>

<dl class="exception">
<dt id="FileNotFoundError">
<em class="property">exception </em><code class="descname">FileNotFoundError</code><a class="headerlink" href="#FileNotFoundError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>要求されたファイルやディレクトリが存在しない場合に送出されます。<code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ENOENT</span></code> に対応します。</p>
</dd></dl>

<dl class="exception">
<dt id="InterruptedError">
<em class="property">exception </em><code class="descname">InterruptedError</code><a class="headerlink" href="#InterruptedError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>システムコールが入力信号によって中断された場合に送出されます。<code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EINTR" title="errno.EINTR"><code class="xref py py-data docutils literal"><span class="pre">EINTR</span></code></a> に対応します。</p>
<div class="versionchanged">
<p><span class="versionmodified">バージョン 3.5 で変更: </span>シグナルハンドラが例外を送出せず、システムコールが信号で中断された場合
Python は <a class="reference internal" href="#InterruptedError" title="InterruptedError"><code class="xref py py-exc docutils literal"><span class="pre">InterruptedError</span></code></a> を送出する代わりにシステムコールを再試行するようになりました (論拠については <span class="target" id="index-8"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0475"><strong>PEP 475</strong></a> を参照してください) 。</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="IsADirectoryError">
<em class="property">exception </em><code class="descname">IsADirectoryError</code><a class="headerlink" href="#IsADirectoryError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>ディレクトリに (<a class="reference internal" href="os.html#os.remove" title="os.remove"><code class="xref py py-func docutils literal"><span class="pre">os.remove()</span></code></a> などの) ファイル操作が要求された場合に送出されます。<code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">EISDIR</span></code> に対応します。</p>
</dd></dl>

<dl class="exception">
<dt id="NotADirectoryError">
<em class="property">exception </em><code class="descname">NotADirectoryError</code><a class="headerlink" href="#NotADirectoryError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>ディレクトリ以外のものに (<a class="reference internal" href="os.html#os.listdir" title="os.listdir"><code class="xref py py-func docutils literal"><span class="pre">os.listdir()</span></code></a> などの) ディレクトリ操作が要求された場合に送出されます。<code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ENOTDIR</span></code> に対応します。</p>
</dd></dl>

<dl class="exception">
<dt id="PermissionError">
<em class="property">exception </em><code class="descname">PermissionError</code><a class="headerlink" href="#PermissionError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>十分なアクセス権、例えばファイルシステム権限のない操作が試みられた場合に送出されます。<code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">EACCES</span></code> および <code class="docutils literal"><span class="pre">EPERM</span></code> に対応します。</p>
</dd></dl>

<dl class="exception">
<dt id="ProcessLookupError">
<em class="property">exception </em><code class="descname">ProcessLookupError</code><a class="headerlink" href="#ProcessLookupError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>与えられたプロセスが存在しない場合に送出されます。<code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ESRCH</span></code> に対応します。</p>
</dd></dl>

<dl class="exception">
<dt id="TimeoutError">
<em class="property">exception </em><code class="descname">TimeoutError</code><a class="headerlink" href="#TimeoutError" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>システム関数がシステムレベルでタイムアウトした場合に送出されます。<code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ETIMEDOUT</span></code> に対応します。</p>
</dd></dl>

<div class="versionadded">
<p><span class="versionmodified">バージョン 3.3 で追加: </span>上記のすべての <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a> サブクラスが追加されました。</p>
</div>
<div class="admonition seealso">
<p class="first admonition-title">参考</p>
<p class="last"><span class="target" id="index-9"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-3151"><strong>PEP 3151</strong></a> - OS および IO 例外階層の手直し</p>
</div>
</div>
</div>
<div class="section" id="warnings">
<h2>5.3. 警告<a class="headerlink" href="#warnings" title="このヘッドラインへのパーマリンク">¶</a></h2>
<p>以下の例外は警告カテゴリとして使われます。詳細については <a class="reference internal" href="warnings.html#module-warnings" title="warnings: Issue warning messages and control their disposition."><code class="xref py py-mod docutils literal"><span class="pre">warnings</span></code></a> モジュールを参照してください。</p>
<dl class="exception">
<dt id="Warning">
<em class="property">exception </em><code class="descname">Warning</code><a class="headerlink" href="#Warning" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>警告カテゴリの基底クラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="UserWarning">
<em class="property">exception </em><code class="descname">UserWarning</code><a class="headerlink" href="#UserWarning" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>ユーザコードによって生成される警告の基底クラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="DeprecationWarning">
<em class="property">exception </em><code class="descname">DeprecationWarning</code><a class="headerlink" href="#DeprecationWarning" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>廃止された機能に対する警告の基底クラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="PendingDeprecationWarning">
<em class="property">exception </em><code class="descname">PendingDeprecationWarning</code><a class="headerlink" href="#PendingDeprecationWarning" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>将来廃止される予定の機能に対する警告の基底クラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="SyntaxWarning">
<em class="property">exception </em><code class="descname">SyntaxWarning</code><a class="headerlink" href="#SyntaxWarning" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>曖昧な構文に対する警告の基底クラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="RuntimeWarning">
<em class="property">exception </em><code class="descname">RuntimeWarning</code><a class="headerlink" href="#RuntimeWarning" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>あいまいなランタイム挙動に対する警告の基底クラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="FutureWarning">
<em class="property">exception </em><code class="descname">FutureWarning</code><a class="headerlink" href="#FutureWarning" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>将来意味構成が変わることになっている文の構成に対する警告の基底クラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="ImportWarning">
<em class="property">exception </em><code class="descname">ImportWarning</code><a class="headerlink" href="#ImportWarning" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>モジュールインポートの誤りと思われるものに対する警告の基底クラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="UnicodeWarning">
<em class="property">exception </em><code class="descname">UnicodeWarning</code><a class="headerlink" href="#UnicodeWarning" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>Unicode に関連した警告の基底クラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="BytesWarning">
<em class="property">exception </em><code class="descname">BytesWarning</code><a class="headerlink" href="#BytesWarning" title="この定義へのパーマリンク">¶</a></dt>
<dd><p><a class="reference internal" href="functions.html#bytes" title="bytes"><code class="xref py py-class docutils literal"><span class="pre">bytes</span></code></a> や <a class="reference internal" href="functions.html#bytearray" title="bytearray"><code class="xref py py-class docutils literal"><span class="pre">bytearray</span></code></a> に関連した警告の基底クラスです。</p>
</dd></dl>

<dl class="exception">
<dt id="ResourceWarning">
<em class="property">exception </em><code class="descname">ResourceWarning</code><a class="headerlink" href="#ResourceWarning" title="この定義へのパーマリンク">¶</a></dt>
<dd><p>リソースの使用に関連した警告の基底クラスです。</p>
<div class="versionadded">
<p><span class="versionmodified">バージョン 3.2 で追加.</span></p>
</div>
</dd></dl>

</div>
<div class="section" id="exception-hierarchy">
<h2>5.4. 例外のクラス階層<a class="headerlink" href="#exception-hierarchy" title="このヘッドラインへのパーマリンク">¶</a></h2>
<p>組み込み例外のクラス階層は以下のとおりです:</p>
<div class="highlight-python3"><div class="highlight"><pre><span></span><span class="ne">BaseException</span>
 <span class="o">+--</span> <span class="ne">SystemExit</span>
 <span class="o">+--</span> <span class="ne">KeyboardInterrupt</span>
 <span class="o">+--</span> <span class="ne">GeneratorExit</span>
 <span class="o">+--</span> <span class="ne">Exception</span>
      <span class="o">+--</span> <span class="ne">StopIteration</span>
      <span class="o">+--</span> <span class="n">StopAsyncIteration</span>
      <span class="o">+--</span> <span class="ne">ArithmeticError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FloatingPointError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">OverflowError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ZeroDivisionError</span>
      <span class="o">+--</span> <span class="ne">AssertionError</span>
      <span class="o">+--</span> <span class="ne">AttributeError</span>
      <span class="o">+--</span> <span class="ne">BufferError</span>
      <span class="o">+--</span> <span class="ne">EOFError</span>
      <span class="o">+--</span> <span class="ne">ImportError</span>
           <span class="o">+--</span> <span class="n">ModuleNotFoundError</span>
      <span class="o">+--</span> <span class="ne">LookupError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IndexError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">KeyError</span>
      <span class="o">+--</span> <span class="ne">MemoryError</span>
      <span class="o">+--</span> <span class="ne">NameError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">UnboundLocalError</span>
      <span class="o">+--</span> <span class="ne">OSError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">BlockingIOError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ChildProcessError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">BrokenPipeError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionAbortedError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionRefusedError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionResetError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FileExistsError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FileNotFoundError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">InterruptedError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IsADirectoryError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">NotADirectoryError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">PermissionError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ProcessLookupError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">TimeoutError</span>
      <span class="o">+--</span> <span class="ne">ReferenceError</span>
      <span class="o">+--</span> <span class="ne">RuntimeError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">NotImplementedError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="n">RecursionError</span>
      <span class="o">+--</span> <span class="ne">SyntaxError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IndentationError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">TabError</span>
      <span class="o">+--</span> <span class="ne">SystemError</span>
      <span class="o">+--</span> <span class="ne">TypeError</span>
      <span class="o">+--</span> <span class="ne">ValueError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">UnicodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeDecodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeEncodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeTranslateError</span>
      <span class="o">+--</span> <span class="ne">Warning</span>
           <span class="o">+--</span> <span class="ne">DeprecationWarning</span>
           <span class="o">+--</span> <span class="ne">PendingDeprecationWarning</span>
           <span class="o">+--</span> <span class="ne">RuntimeWarning</span>
           <span class="o">+--</span> <span class="ne">SyntaxWarning</span>
           <span class="o">+--</span> <span class="ne">UserWarning</span>
           <span class="o">+--</span> <span class="ne">FutureWarning</span>
           <span class="o">+--</span> <span class="ne">ImportWarning</span>
           <span class="o">+--</span> <span class="ne">UnicodeWarning</span>
           <span class="o">+--</span> <span class="ne">BytesWarning</span>
           <span class="o">+--</span> <span class="ne">ResourceWarning</span>
</pre></div>
</div>
</div>
</div>


          </div>
        </div>
      </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
  <h3><a href="../contents.html">目次</a></h3>
  <ul>
<li><a class="reference internal" href="#">5. 組み込み例外</a><ul>
<li><a class="reference internal" href="#base-classes">5.1. 基底クラス</a></li>
<li><a class="reference internal" href="#concrete-exceptions">5.2. 具象例外</a><ul>
<li><a class="reference internal" href="#os-exceptions">5.2.1. OS 例外</a></li>
</ul>
</li>
<li><a class="reference internal" href="#warnings">5.3. 警告</a></li>
<li><a class="reference internal" href="#exception-hierarchy">5.4. 例外のクラス階層</a></li>
</ul>
</li>
</ul>

  <h4>前のトピックへ</h4>
  <p class="topless"><a href="stdtypes.html"
                        title="前の章へ">4. 組み込み型</a></p>
  <h4>次のトピックへ</h4>
  <p class="topless"><a href="text.html"
                        title="次の章へ">6. テキスト処理サービス</a></p>
  <div role="note" aria-label="source link">
    <h3>このページ</h3>
    <ul class="this-page-menu">
      <li><a href="../bugs.html">バグ報告</a></li>
      <li>
        <a href="https://github.com/python/cpython/blob/3.6/Doc/library/exceptions.rst"
            rel="nofollow">ソースの表示
        </a>
      </li>
    </ul>
  </div>
        </div>
      </div>
      <div class="clearer"></div>
    </div>  
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>ナビゲーション</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="総索引"
             >索引</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Pythonモジュール索引"
             >モジュール</a> |</li>
        <li class="right" >
          <a href="text.html" title="6. テキスト処理サービス"
             >次へ</a> |</li>
        <li class="right" >
          <a href="stdtypes.html" title="4. 組み込み型"
             >前へ</a> |</li>
        <li><img src="../_static/py.png" alt=""
                 style="vertical-align: middle; margin-top: -1px"/></li>
        <li><a href="https://www.python.org/">Python</a> &#187;</li>
        <li>
          <span class="version_switcher_placeholder">3.6.1</span>
          <a href="../index.html">ドキュメント</a> &#187;
        </li>

          <li class="nav-item nav-item-1"><a href="index.html" >Python 標準ライブラリ</a> &#187;</li>
    <li class="right">
        

    <div class="inline-search" style="display: none" role="search">
        <form class="inline-search" action="../search.html" method="get">
          <input placeholder="Quick search" type="text" name="q" />
          <input type="submit" value="Go" />
          <input type="hidden" name="check_keywords" value="yes" />
          <input type="hidden" name="area" value="default" />
        </form>
    </div>
    <script type="text/javascript">$('.inline-search').show(0);</script>
         |
    </li>

      </ul>
    </div>  
    <div class="footer">
    &copy; <a href="../copyright.html">Copyright</a> 2001-2017, Python Software Foundation.
    <br />
    Python Software Foundation は非営利団体です。
    <a href="https://www.python.org/psf/donations/">寄付</a>
    <br />
    最終更新日時: 4月 17, 2017
    <a href="../bugs.html">バグを見つけたら</a>?
    <br />
    このドキュメントは <a href="http://sphinx.pocoo.org/">Sphinx</a> 1.4.9 を使って作成されました。
    </div>

  </body>
</html>